name: 'Run Tests'

on: 
  push:
    paths:
      - src/**
      - makefile
  pull_request:
    paths:
      - src/**
      - makefile

jobs:
  run-test:
    runs-on: self-hosted
    steps:
      - name: Install Nix 
        uses: cachix/install-nix-action@v18 
        
      - name: Clone Fundament Scopes
        run: git clone https://github.com/fundament-software/scopes
      
      - name: Build & Install Scopes
        run: | 
          cd scopes
          nix build
      
      - name: Add Scopes to Path
        run:
          echo "$GITHUB_WORKSPACE/scopes/result/bin" >> $GITHUB_PATH

      - name: Clone Repository
        run: git clone https://github.com/queercat/sc-bench-utils
      
      - name: Run Tests
        run: |
          cd sc-bench-utils
          make test
